VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define "pipeline01" do |pipeline01|
    pipeline01.vm.box = "ubuntu/bionic64"
    pipeline01.vm.hostname = "pipeline01"
    pipeline01.vm.network :forwarded_port, guest: 22, host: 3301, id: "ssh"
    pipeline01.vm.network :private_network, ip: "10.11.12.20"
    pipeline01.vm.network :private_network, ip: "192.168.12.20", virtualbox__intnet: true
  end

  config.vm.define "pipeline02" do |pipeline02|
    pipeline02.vm.box = "ubuntu/bionic64"
    pipeline02.vm.hostname = "pipeline02"
    pipeline02.vm.network :forwarded_port, guest: 22, host: 3302, id: "ssh"
    pipeline02.vm.network :private_network, ip: "10.11.12.21"
    pipeline02.vm.network :private_network, ip: "192.168.12.21", virtualbox__intnet: true
  end

end